# Generated by Django 3.2.7 on 2021-11-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=250)),
                ('farm_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('department', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('farmer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.farmers')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('farmer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.farmers')),
            ],
        ),
    ]
