# Generated by Django 3.2.7 on 2021-11-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='staff_name',
        ),
    ]
