# Generated by Django 3.2.7 on 2021-11-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_remove_records_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='title',
            field=models.CharField(default='describe the type of tea', max_length=250),
        ),
    ]
