# Generated by Django 3.2.7 on 2021-11-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_records_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='title',
            field=models.CharField(default='farmer', max_length=100),
        ),
    ]
